/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FreightRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Freight.Freight;
import Business.Organisation.FreightOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.Validator.ValidatorClass;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pratik Singh <pratiksingh>
 */
public class CreateFreight extends javax.swing.JPanel {

    FreightOrganisation organisation;
    JPanel userProcessContainer;

    /**
     * Creates new form CreateFreight
     */

    public CreateFreight(JPanel userProcessContainer, UserAccount account, EcoSystem system, Organisation organisation, Enterprise enterprise) {
        initComponents();
        this.organisation = (FreightOrganisation) organisation;
        this.userProcessContainer = userProcessContainer;
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fInsurence = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        freightNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        model = new javax.swing.JTextField();
        capacityTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("Add Trailer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Add Trailer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Capacity(tons)*:");

        jLabel1.setText("Trailer Number*:");

        jLabel3.setText("Freight Insurance*:");

        jLabel5.setText("Type:");

        freightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freightNumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Freight Model(YYYY)*:");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mini Van", "12 Wheeler", "16 Wheeler", "18 Wheeler" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(freightNumber)
                    .addComponent(capacityTxt)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fInsurence, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(freightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(fInsurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(capacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fInsurence, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(freightNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(model, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(capacityTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(206, 206, 206)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
        try{
        ValidatorClass validator = new ValidatorClass();

        boolean isfempty = validator.isEmpty(freightNumber.getText());
        boolean isInsure = validator.isEmpty(fInsurence.getText());
        boolean isCapacity = validator.isEmpty(capacityTxt.getText());
        boolean ismodel = validator.isEmpty(String.valueOf(model.getText()));

        boolean isinsnumber = validator.isNumber(fInsurence.getText());
        boolean iscapacity = validator.isNumber(capacityTxt.getText());
        boolean isModel = validator.is4DgitNumber(model.getText());

        boolean flag = false;

        if (isfempty || isInsure || isCapacity || ismodel) {
            JOptionPane.showMessageDialog(null, "Please enter all the mandetory fields", "Error", JOptionPane.ERROR_MESSAGE);

        } else if (!isinsnumber || !iscapacity) {
            JOptionPane.showMessageDialog(null, "Capacity and insurence should be a number", "Error", JOptionPane.ERROR_MESSAGE);

        } else if (!isModel) {
            JOptionPane.showMessageDialog(null, "model should be a year in YYYY format", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            
                int capacity = Integer.parseInt(capacityTxt.getText());
        int insurance = Integer.parseInt(fInsurence.getText());
        int date = Integer.parseInt(model.getText());
        
        if(insurance>9000||insurance<=0)
        {
        JOptionPane.showMessageDialog(null,"The insurance should be in the range of 1 to 1000","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
           if(date>2015||date<=2011)
        {
        JOptionPane.showMessageDialog(null,"The Date should be in the range of 2012 to 2015","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
           
        if(capacity>100||date<=0)
        {
        JOptionPane.showMessageDialog(null,"The Capacity should be in the range of 0 to 100","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }

            for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
                if (freight.getfNumber().toString().equalsIgnoreCase(freightNumber.getText())) {
                    JOptionPane.showMessageDialog(null, "The freight already exists", "Error", JOptionPane.ERROR_MESSAGE);
                    flag = true;
                    resetFields();
                    break;
                }
            }

            if (!flag) {
                Freight freight = new Freight();
                freight.setfCapacity(Integer.parseInt(capacityTxt.getText()));
                freight.setfNumber(freightNumber.getText());
                freight.setFreightModel(Integer.parseInt(model.getText()));
                freight.setFreightInsureNumber(Integer.parseInt(fInsurence.getText()));
                freight.setFreightType((String) type.getSelectedItem());
                freight.setfLoaded(false);

                organisation.getFreightDir().addFreight(freight);

                JOptionPane.showMessageDialog(null, "Trailer has been added successfully", "INFO", JOptionPane.INFORMATION_MESSAGE);
                resetFields();
            }
        }
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "Invalid Input","Try again",JOptionPane.ERROR_MESSAGE);
        freightNumber.setText("");
        capacityTxt.setText("");
        fInsurence.setText("");
        model.setText("");
        System.out.println("Invalid input. Please try again");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void resetFields() {
        capacityTxt.setText("");
        freightNumber.setText("");
        fInsurence.setText("");
        model.setText("");

    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void freightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freightNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freightNumberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityTxt;
    private javax.swing.JTextField fInsurence;
    private javax.swing.JTextField freightNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField model;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
