/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FreightRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Freight.Freight;
import Business.Organisation.FreightOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik Singh <pratiksingh>
 */
public class FreightLocation extends javax.swing.JPanel {

    FreightOrganisation organisation;
    JPanel userProcessContainer;

    /**
     * Creates new form FreightLocation
     */
    public FreightLocation(JPanel userProcessContainer, UserAccount account, FreightOrganisation organisation, EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.organisation = organisation;
        this.userProcessContainer = userProcessContainer;
        populateTable();
        imageScale();
    }

    public void imageScale() {

        BufferedImage img = null;

        try {
            img = ImageIO.read(new File("staticmap.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        //img = ImageIO.read(new File("C:\\Users\\Deryl\\Desktop\\ImagesJava\\warehouse.jpg"));
//       

//       
        //BufferedImage dimg =  ImageIO.read(img); 
        javax.swing.ImageIcon imageIcon = new javax.swing.ImageIcon(img);
        java.awt.Image originalImage = imageIcon.getImage();
        java.awt.Image scaledImage = originalImage.getScaledInstance(450, 450, java.awt.Image.SCALE_SMOOTH);

        javax.swing.ImageIcon newIconImage = new javax.swing.ImageIcon(scaledImage);
        //  staticMapJlabel.setPreferredSize(new java.awt.Dimension(200,600));
        staticMapJlabel.setIcon(newIconImage);
        staticMapJlabel.setText("");

// 
//    
//       BufferedImage img = null;
//        try {
//            img = ImageIO.read(new File("C:\\Users\\Deryl\\Desktop\\ImagesJava\\warehouse.jpg"));
//       } catch (IOException e) {
//          e.printStackTrace();
//        }
//
//        BufferedImage dimg =  ImageIO.read(file);;
//
//       ImageIcon imageIcon = new ImageIcon(dimg);
//       jLabel1.setIcon(imageIcon);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
            Object[] row = new Object[1];
            row[0] = freight;

            model.addRow(row);

            //freightTable
        }

        if (model.getRowCount() == 0) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        staticMapJlabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Freight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staticMapJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staticMapJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(staticMapJlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("View location of all the Trailer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Track the Current Location of the Trailer");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("MAP:");

        jLabel3.setText("Click on the trailer below to see the location on the map:");

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(779, 779, 779))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        viewAll();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        populateMap();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //         userProcessContainer.remove(this);
        //        Component[] componentArray = userProcessContainer.getComponents();
        //        Component component = componentArray[componentArray.length - 1];
        //        WarehouseWorkAreaJPanel dwjp = (WarehouseWorkAreaJPanel) component;
        //        //dwjp.populateRequestTable();
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateMap() {

        System.out.println("inside loop");

        try {
            Image image = javax.imageio.ImageIO.read(new File("staticmap.jpg"));
            System.out.println("image storeed");
            image = image.getScaledInstance(450, 450, Image.SCALE_SMOOTH);

            System.out.println("image scaled");
            BufferedImage newimg = new BufferedImage(450, 450, BufferedImage.TYPE_INT_ARGB);

            System.out.println("image buffered");
            Graphics2D graphics = newimg.createGraphics();

            graphics.drawImage(image, 0, 0, null);
            graphics.drawImage(image, 500, 0, null);
            graphics.setColor(Color.RED);

            System.out.println("image graph created");

            int selRow = jTable1.getSelectedRow();

            Freight freight = (Freight) jTable1.getValueAt(selRow, 0);

//initial values
//latitude =38.79992651
///longitude = -77.1908766
//latitude 450.0 * (38.74882651 -(38.8992651-0.2)) / 0.4
//Longitude 450.0 * (-77.1908766-(-77.0546514-0.2)) / 0.4
//56
            int x = (int) (freight.getLocationSensor().getLatitude());
            int y = (int) (freight.getLocationSensor().getLongitude());

            graphics.fillRect(y, x, 20, 20);
            graphics.drawString(freight.getfNumber().toString(), y, x);

            //System.out.println(y + "   " + latitude);
            ImageIO.write(newimg, "png", new File("output.png"));

            System.out.println("Output printed");
        } catch (Exception e) {
            System.out.println("Problem in image handling");
        }
        try {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("output.png").getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));
            staticMapJlabel.setIcon(imageIcon);
            System.out.print(imageIcon.getIconHeight() + " " + imageIcon.getIconWidth());
        } catch (Exception e) {
            System.out.println("Problem in image saing");
        }

    }

    public void viewAll() {

        System.out.println("inside loop");

        try {
            try {
                Image image = javax.imageio.ImageIO.read(new File("staticmap.jpg"));
                System.out.println("image storeed");
                image = image.getScaledInstance(450, 450, Image.SCALE_SMOOTH);

                System.out.println("image scaled");
                BufferedImage newimg = new BufferedImage(450, 450, BufferedImage.TYPE_INT_ARGB);

                System.out.println("image buffered");
                Graphics2D graphics = newimg.createGraphics();

                graphics.drawImage(image, 0, 0, null);
                graphics.drawImage(image, 500, 0, null);
                graphics.setColor(Color.RED);

                System.out.println("image graph created");

                int selRow = jTable1.getSelectedRow();

//            Freight freight = (Freight) jTable1.getValueAt(selRow, 0);
                for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
//initial values
//latitude =38.79992651
///longitude = -77.1908766
//latitude 450.0 * (38.74882651 -(38.8992651-0.2)) / 0.4
//Longitude 450.0 * (-77.1908766-(-77.0546514-0.2)) / 0.4
//56
                    int latitude = (int) (freight.getLocationSensor().getLatitude());
                    int longitude = (int) (freight.getLocationSensor().getLongitude());
                    graphics.fillRect(longitude, latitude, 20, 20);

                    graphics.drawString(freight.getfNumber().toString(), longitude, latitude);
                    System.out.println(longitude + "   " + latitude);
                }
                ImageIO.write(newimg, "png", new File("output.png"));

                System.out.println("Output printed");
            } catch (Exception e) {
                System.out.println("Problem in image handling");
            }
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("output.png").getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));
            staticMapJlabel.setIcon(imageIcon);
            System.out.print(imageIcon.getIconHeight() + " " + imageIcon.getIconWidth());
        } catch (Exception e) {
            System.out.println("F in viewing");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel staticMapJlabel;
    // End of variables declaration//GEN-END:variables
}
