/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AnalystFreight;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Freight.Freight;
import Business.FreightSensor.SensorOverallHealth;
import Business.Organisation.FreightOrganisation;
import Business.Organisation.Organisation;

import Business.UserAccount.UserAccount;
import UserInterface.FreightRole.FreightLocation;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.data.time.Year;

/**
 *
 * @author Pratik Singh <pratiksingh>
 */
public class FreightAnalystJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    FreightOrganisation organisation;
    Enterprise enterprise;

    /**
     * Creates new form FreightAnalystJPanel
     */
    public FreightAnalystJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, Organisation organisation, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        this.organisation = (FreightOrganisation) organisation;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) freightTable.getModel();
        model.setRowCount(0);

        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
            Object[] row = new Object[1];
            row[0] = freight;

            model.addRow(row);

            //freightTable
        }
    }

    public void topFreight() {
        Map<Integer, Freight> count1 = new HashMap<Integer, Freight>();
        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
            int x = freight.getfCondition().getEngineEmmision();
            count1.put(x, freight);

        }

        TreeMap<Integer, Freight> treeMap = new TreeMap<Integer, Freight>(
                new Comparator<Integer>() {

                    @Override
                    public int compare(Integer o1, Integer o2) {
                        return o1.compareTo(o2);
                    }

                });

        treeMap.putAll(count1);
        DefaultTableModel model = (DefaultTableModel) freightTable1.getModel();

        model.setRowCount(0);
        int i = 0;
        for (Map.Entry<Integer, Freight> entry : treeMap.entrySet()) {

            Object[] row = new Object[3];
            row[0] = entry.getValue();
            row[1] = entry.getKey();
            model.addRow(row);

            i++;
            if (i == 3) {
                break;
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredpaneMain = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        freightTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        frontTyreTxt5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        frontTyreTxt4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        maintenanceTxt = new javax.swing.JTextField();
        frontTyreTxt6 = new javax.swing.JLabel();
        overallhealthTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField3 = new javax.swing.JTextField();
        fTyreTxt = new javax.swing.JTextField();
        frontTyreTxt7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        rTyreTxt = new javax.swing.JTextField();
        frontTyreTxt = new javax.swing.JLabel();
        frontTyreTxt1 = new javax.swing.JLabel();
        frontTyreTxt3 = new javax.swing.JLabel();
        frontTyreTxt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        freightTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        freightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Freight"
            }
        ));
        freightTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freightTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(freightTable);

        jButton1.setText("Stimulate Sensor Data");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        frontTyreTxt5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        frontTyreTxt5.setText("%");

        jButton2.setText("Graphical Representation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        frontTyreTxt4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frontTyreTxt4.setText("Co2 Emission");

        jTextField1.setEnabled(false);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frontTyreTxt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontTyreTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frontTyreTxt4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frontTyreTxt5)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jLayeredPane2.setLayer(frontTyreTxt5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(frontTyreTxt4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        frontTyreTxt6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frontTyreTxt6.setText("Overall Health");

        overallhealthTxt.setEnabled(false);

        jButton3.setText("View Past Records");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(frontTyreTxt6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overallhealthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(maintenanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frontTyreTxt6)
                    .addComponent(overallhealthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );
        jLayeredPane3.setLayer(maintenanceTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(frontTyreTxt6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(overallhealthTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fTyreTxt.setEnabled(false);

        frontTyreTxt7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frontTyreTxt7.setText("Following shows the details of front wheels and the rear wheels");

        rTyreTxt.setEnabled(false);

        frontTyreTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frontTyreTxt.setText("Air Front Tyre");

        frontTyreTxt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frontTyreTxt1.setText("Rear Tyre");

        frontTyreTxt3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        frontTyreTxt3.setText("PSI");

        frontTyreTxt2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        frontTyreTxt2.setText("PSI");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(frontTyreTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(frontTyreTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(fTyreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frontTyreTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frontTyreTxt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(rTyreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frontTyreTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(frontTyreTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frontTyreTxt)
                        .addComponent(fTyreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(frontTyreTxt2))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frontTyreTxt1)
                        .addComponent(rTyreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(frontTyreTxt3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fTyreTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(frontTyreTxt7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rTyreTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(frontTyreTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(frontTyreTxt1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(frontTyreTxt3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(frontTyreTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Top 3 Ecofriendly Freights");

        freightTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Freight", "Carbon Monoxide Released"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        freightTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freightTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(freightTable1);

        jButton4.setText("Track Location");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layeredpaneMainLayout = new javax.swing.GroupLayout(layeredpaneMain);
        layeredpaneMain.setLayout(layeredpaneMainLayout);
        layeredpaneMainLayout.setHorizontalGroup(
            layeredpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredpaneMainLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layeredpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layeredpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLayeredPane3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1)
                        .addComponent(jLayeredPane2)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
        layeredpaneMainLayout.setVerticalGroup(
            layeredpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredpaneMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(44, 44, 44))
        );
        layeredpaneMain.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredpaneMain.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(layeredpaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(layeredpaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void feightSensorsetting() {
        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
            int lat = randomLatitude();
            int longi = randomLongitude();
            System.out.println("freight " + freight);
            freight.getLocationSensor().setLatitude(lat);
            freight.getLocationSensor().setLatitude(longi);
        }
    }

    public int randomLatitude() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(390 - 30) + 30;
        return x;
    }

    public int randomLongitude() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(390 - 30) + 30;
        return x;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            dateFormat();
            feightSensorsetting();
            for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
                if (freight.getfCondition() == null) {
                } else {
                    int x = randomDataFor();
                    freight.getfCondition().setFrontAir(x);
                    int y = randomDataFor();
                    freight.getfCondition().setRearAir(y);
                    int z = randomDataForCO();
                    freight.getfCondition().setEngineEmmision(z);
                }
            }

            topFreight();
        } catch (Exception e) {
            System.out.println("Problem");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public int randomDataForFreightHealt() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(55 - 20) + 20;
        return x;
    }

    public void dateFormat() {

        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {

            if (freight.getfHealth() == null) {
                System.out.println("The fHealt is not initialised");
            } else {
                for (int i = 0; i < freight.getfHealth().size(); i++) {
                    freight.getfHealth().remove(i);
                }

                int j = 0;
                for (int i = 2005; i < 2015; i++) {

                    freight.getfHealth().add(new SensorOverallHealth());
                    freight.getfHealth().get(j).setFyear(String.valueOf(i));
                    int x = randomDataForFreightHealt();
                    freight.getfHealth().get(j).setfHealth(x);
                    j++;
                }
            }
        }

        //for testing the code for Date saving 
//        for (Freight freight : organisation.getFreightDir().getFreightDirectory()) {
//            if (freight.getfHealth() == null) {
//            } else {
//                for (int i = 0; i < 10; i++) {
//                    System.out.println(freight.toString());
//                    System.out.println(freight.getfHealth().get(i).getFyear());
//                    System.out.println(freight.getfHealth().get(i).getfHealth());
//
//                }
//            }
//        }
        populateTable();

    }


    private void freightTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freightTableMouseClicked
        try {        // TODO add your handling code here:
            int selVal = freightTable.getSelectedRow();
            if (selVal < 0) {

            } else {

                Freight freight = (Freight) freightTable.getValueAt(selVal, 0);
                fTyreTxt.setText(String.valueOf(freight.getfCondition().getFrontAir()));
                rTyreTxt.setText(String.valueOf(freight.getfCondition().getRearAir()));
                jTextField1.setText(String.valueOf(freight.getfCondition().getEngineEmmision()));

                for (int i = 0; i < 10; i++) {
                    if (freight.getfHealth().get(i).getFyear().equals("2014")) {

                        overallhealthTxt.setText(String.valueOf(freight.getfHealth().get(i).getfHealth()));
                    }

                }
//            for (int i = 0; i < freight.getfHealth().size(); i++) {
//                if (freight.getfHealth().get(i).getFyear().equals("2014")) {
//                    overallhealthTxt.setText(String.valueOf(freight.getfHealth().get(i).getfHealth()));
//                }
//            }
                if (Integer.parseInt(overallhealthTxt.getText()) < 50) {

                    maintenanceTxt.setText("Servicing Required");
                    maintenanceTxt.setBackground(Color.RED);
                } else {
                    maintenanceTxt.setText("Normal");
                    maintenanceTxt.setBackground(Color.WHITE);
                }
                if (freight.getfCondition().getFrontAir() < 75) {

                    jTextField2.setText("Check");
                } else {
                    jTextField2.setText("Normal");
                }
                if (freight.getfCondition().getRearAir() < 75) {

                    jTextField3.setText("Check");
                } else {
                    jTextField3.setText("Normal");
                }

                jTextField1.setText(String.valueOf(freight.getfCondition().getEngineEmmision()));

            }
        } catch (Exception e) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_freightTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        System.out.println(dateFormat.format(date)); //2014/08/06 15:59:48

        DefaultPieDataset pieDataSet = new DefaultPieDataset();
        pieDataSet.setValue("Co2 Emmision", new Integer(Integer.parseInt(jTextField1.getText())));
        int nitrogen = randomDataFornitrogenOxide();
        int hydrocarbon = randomDataFornitrogenOxide();
        int volatileOrganiccompound = randomDataFornitrogenOxide();
        pieDataSet.setValue("Nitrogen Oxide (NO)", new Integer(nitrogen));
        pieDataSet.setValue("Hydrocarbon (CXHX)", new Integer(hydrocarbon));
        pieDataSet.setValue("Other Volatile Gases", new Integer(volatileOrganiccompound));
        pieDataSet.setValue("O2", new Integer(100 - Integer.parseInt(jTextField1.getText()) - nitrogen - hydrocarbon - volatileOrganiccompound));

        JFreeChart chart = ChartFactory.createPieChart3D("Emission of Various Gases:Data recorded from the sensors as of " + date, pieDataSet, true, true, true);
        PiePlot3D p = (PiePlot3D) chart.getPlot();
        // p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(950, 950);
}catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Click on the row to select the freight","ERROR",JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    public int randomDataForVolatileOrganic() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(5 - 1) + 1;
        return x;
    }

    public int randomDataFornitrogenOxide() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(20 - 10) + 10;
        return x;
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
try{
        int selRow = freightTable.getSelectedRow();

        if (selRow < 0) {

        } else {
            Freight freight = (Freight) freightTable.getValueAt(selRow, 0);

            TimeSeries health = new TimeSeries("Health", Year.class);

            for (int j = 0; j < 10; j++) {
                int i = Integer.parseInt(freight.getfHealth().get(j).getFyear());
                health.add(new Year(i), freight.getfHealth().get(j).getfHealth());

            }

            TimeSeriesCollection dataset = new TimeSeriesCollection();
            dataset.addSeries(health);

            JFreeChart chart = ChartFactory.createTimeSeriesChart(
                    "Graph",
                    "Time",
                    "Health",
                    dataset,
                    true,
                    true,
                    false);

            ChartFrame chartFrame = new ChartFrame("Health for Trailer", chart);
            chartFrame.setVisible(true);
            chartFrame.setSize(550, 450);

        }
}catch(Exception e)
{

JOptionPane.showMessageDialog(null,"Click on the row to select the freight","ERROR",JOptionPane.ERROR_MESSAGE);

}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void freightTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freightTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_freightTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FreightLocation freightLocation = new FreightLocation(userProcessContainer, account, organisation, system, enterprise);
        userProcessContainer.add("Get freight location", freightLocation);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_jButton4ActionPerformed

    public int randomDataFor() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(80 - 70) + 70;
        return x;
    }

    public int randomDataForCO() {
        int x = 0;
        Random rand = new Random();
        x = rand.nextInt(40 - 10) + 10;
        return x;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fTyreTxt;
    private javax.swing.JTable freightTable;
    private javax.swing.JTable freightTable1;
    private javax.swing.JLabel frontTyreTxt;
    private javax.swing.JLabel frontTyreTxt1;
    private javax.swing.JLabel frontTyreTxt2;
    private javax.swing.JLabel frontTyreTxt3;
    private javax.swing.JLabel frontTyreTxt4;
    private javax.swing.JLabel frontTyreTxt5;
    private javax.swing.JLabel frontTyreTxt6;
    private javax.swing.JLabel frontTyreTxt7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLayeredPane layeredpaneMain;
    private javax.swing.JTextField maintenanceTxt;
    private javax.swing.JTextField overallhealthTxt;
    private javax.swing.JTextField rTyreTxt;
    // End of variables declaration//GEN-END:variables
}
